name: Generate Artifact
run-name: Generate Artifact Demo

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        default: "user"
      environment:
        type: choice
        options:
          - production
          - staging
          - testing
        default: "staging"

jobs:
  generate_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Create File
        run: |
          echo "Hello, ${{ github.event.inputs.name }}!" > artifact.txt
          echo "Environment: ${{ github.event.inputs.environment }}" >> artifact.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: user-inputs
          path: artifact.txt
