name: Ollama cache v1

on:
  workflow_dispatch: # Allows running this workflow manually from the Actions tab

permissions:
  contents: read

jobs:
  run_ollama:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Get Ollama version
      - name: Get Ollama version
        id: get-ollama-version
        run: |
          if command -v ollama &> /dev/null; then
            ollama_version=$(ollama --version)
            echo "Ollama version: $ollama_version"
            echo "version=$ollama_version" >> $GITHUB_ENV
          else
            ollama_version="none"
            echo "No Ollama installed"
            echo "version=$ollama_version" >> $GITHUB_ENV
          fi

      # Cache the Ollama binary and version
      - name: Cache Ollama binary and version
        id: ollama-cache
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/ollama
          key: ${{ runner.os }}-ollama-version-${{ env.version }}

      # Install Ollama if not cached
      - name: Install Ollama
        if: steps.ollama-cache.outputs.cache-hit != 'true'
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
