name: Install and Run Ollama

on:
    workflow_dispatch: # Allows running this workflow manually from the Actions tab

permissions:
    contents: read

jobs:
    # Stage 1: Checkout and install dependencies
    install_dependencies:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Ollama
              run: |
                  curl -fsSL https://ollama.com/install.sh | sh

            - name: Install Go
              run: |
                  sudo apt update
                  sudo apt install -y golang-go

    # Stage 2: Save Ollama version and start the server
    setup_ollama:
        runs-on: ubuntu-latest
        needs: install_dependencies # Depends on the previous job
        steps:
            - name: Save Ollama version
              run: |
                  ollama --version > ollama_version.txt

            - name: Run Ollama server in the background
              run: |
                  nohup ollama serve & # Start Ollama server in the background
                  sleep 10 # Give it some time to start

    # Stage 3: Run the Ollama model
    run_ollama:
        runs-on: ubuntu-latest
        needs: setup_ollama # Depends on the previous job
        steps:
            - name: Run llama model
              run: |
                  ollama run llama3.1

    # Stage 4: Build the Go script
    build_go_script:
        runs-on: ubuntu-latest
        needs: run_ollama # Depends on the previous job
        steps:
            - name: Build Go script
              run: |
                  go build -o query-ollama query-ollama.go

    # Stage 5: Finalize and execute Go script
    finalize_and_run:
        runs-on: ubuntu-latest
        needs: build_go_script # Depends on the previous job
        steps:
            - name: Make Go script executable
              run: |
                  chmod +x query-ollama

            - name: Verify file permissions
              run: |
                  ls -la query-ollama

            - name: Run Go script
              run: |
                  ./query-ollama
