name: Install and Run Ollama

on:
    workflow_dispatch: # Allows running this workflow manually from the Actions tab

permissions:
    contents: read

jobs:
    run_ollama:
        runs-on: ubuntu-latest

        steps:
            - name: Install Ollama
              run: |
                  curl -fsSL https://ollama.com/install.sh | sh
              
            - name: Save Ollama version
              run: |
                  ollama --version > ollama_version.txt

            - name: Run Ollama server in the background
              run: |
                  nohup ollama serve & # Start Ollama server in the background
                  sleep 10 # Give it some time to start

            - name: Run llama model
              run: |
                  ollama run llama3.1

            - name: Install Go
              run: |
                  sudo apt update
                  sudo apt install -y golang-go

            - name: Run Go script
              run: |
                  ./query-ollama
