name: Ollama cache v1

on:
  workflow_dispatch: # Allows running this workflow manually from the Actions tab

permissions:
  contents: read

jobs:
  run_ollama:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache the Ollama binary with a general key before knowing the version
      - name: Cache Ollama binary
        id: ollama-cache
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/ollama
          key: ${{ runner.os }}-ollama
          restore-keys: ${{ runner.os }}-ollama-

      # Install Ollama if not cached
      - name: Install Ollama
        if: steps.ollama-cache.outputs.cache-hit != 'true'
        run: |
          curl -fsSL https://ollama.com/install.sh | sh

      # Get Ollama version after installation
      - name: Get Ollama version
        id: get-ollama-version
        run: |
          ollama_version=$(ollama --version 2>&1 | grep -oP '(?<=version )[\d.]+')
          echo "Ollama version: $ollama_version"
          echo "version=$ollama_version" >> $GITHUB_ENV

      # Re-cache the Ollama binary and version (now we know the version)
      - name: Update Ollama cache with version
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/ollama
          key: ${{ runner.os }}-ollama-${{ env.version }}
          restore-keys: ${{ runner.os }}-ollama-
