name: Install and Run Ollama v2

on:
  workflow_dispatch: # Allows running this workflow manually from the Actions tab

permissions:
  contents: read

jobs:
  run_ollama:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache the Ollama binary directory
      - name: Cache Ollama binary
        id: ollama-cache
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/ollama
          key: ${{ runner.os }}-ollama-${{ hashFiles('ollama_version.txt') }}

      # Install Ollama if not cached
      - name: Install Ollama
        if: steps.ollama-cache.outputs.cache-hit != 'true'
        run: |
          curl -fsSL https://ollama.com/install.sh | sh

      # Save Ollama version
      - name: Save Ollama version
        run: |
          ollama --version > ollama_version.txt

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20' # Adjust the version as needed

      # Build Go script
      - name: Build Go script
        run: |
          go build -o query-ollama query-ollama.go

      # Make Go script executable
      - name: Make Go script executable
        run: |
          chmod +x query-ollama

      # Verify file permissions
      - name: Verify file permissions
        run: |
          ls -la query-ollama

      # Run Ollama server in the background
      - name: Run Ollama server in the background
        run: |
          nohup ollama serve & # Start Ollama server in the background
          sleep 10 # Give it some time to start

      # Run llama model
      - name: Run llama model
        run: |
          ollama run llama3.1

      # Run Go script
      - name: Run Go script
        run: |
          ./query-ollama
