name: Reusable Workflow
run-name: Reusable Workflow

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  default_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Step
        run: echo '${{ fromJSON(inputs.job-steps) }}'
