name: Reusable Workflow
run-name: Reusable Workflow

on:
  workflow_call:
    inputs:
      job-steps:
        required: true
        type: string

jobs:
  default_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        step: ${{ fromJSON(inouts.job-steps) }}
    steps:
      - name: Run Step
        run: ${{ matrix.step.run }}
