name: Reusable Workflow
run-name: Reusable Workflow

on:
  workflow_call:
    inputs:
      job-steps:
        required: true
        type: string

jobs:
  default_job:
    runs-on: ubuntu-latest
    steps: ${{ fromJSON(inputs.job-steps) }}
