name: Reusable Workflow
run-name: Reusable Workflow

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  default_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Message received: ${{ inputs.message }}"
