name: rjip Test Workflow

on:
    schedule:
        - cron: "27 2 * * *" # Run every day at 11:43 PM UTC

permissions:
    contents: write # Allow workflow to push changes
    id-token: write # Allow workflow to use the ID token

jobs:
    execute_script:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Download data.json
              uses: ./.github/actions/download-data

            - name: Clone rjip repository
              uses: ./.github/actions/clone-rjip

            - name: Run rjip command and handle output
              uses: ./.github/actions/run-rjip

            - name: Commit changes
              if: env.commit_changes == 'true'
              run: |
                  echo "Committing changes..."
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git add item.json last_picks.json
                  git commit -m "Add item.json and update last_picks.json"
                  git push
